DROP TABLE TSK_BROKEN_PROCESSES;
DROP SEQUENCE  SEQ_TSK_BROKEN_PROCESSES;

DROP SEQUENCE QB$SEQUENCE;
DROP SEQUENCE QB$CHECKPOINT_SEQUENCE;
DROP SEQUENCE SEQ_TSK_SCHEDULED;
DROP TABLE TSK_SCHEDULED;
DROP TABLE QB$QUEUE_NAMES;
DROP TABLE DECISION;
DROP TABLE TR_CHECKPOINTS;
DROP TABLE GRAPH;
DROP TABLE GRAPH_DECISION;
DROP TABLE TASK;
DROP TABLE PROCESS;

exit;