CREATE INDEX TASKUROTTA.idx$dec_date ON TASKUROTTA.DECISION (DECISION_DATE);

CREATE INDEX TASKUROTTA.idx$is_error ON TASKUROTTA.DECISION (IS_ERROR);

CREATE INDEX TASKUROTTA.idx$actor_id ON TASKUROTTA.TASK (ACTOR_ID ASC);

CREATE INDEX TASKUROTTA.idx$start_time ON TASKUROTTA.TASK (START_TIME ASC);

CREATE INDEX TASKUROTTA.idx$process_start ON TASKUROTTA.PROCESS (START_TIME ASC);

CREATE INDEX TASKUROTTA.idx$process_state ON TASKUROTTA.PROCESS (STATE ASC);

