DROP SEQUENCE QB$SEQUENCE;
DROP SEQUENCE QB$CHECKPOINT_SEQUENCE;
DROP TABLE QB$QUEUE_NAMES;
DROP TABLE DECISION;
DROP TABLE TR_CHECKPOINTS;
DROP TABLE GRAPH;
DROP TABLE GRAPH_DECISION;
DROP TABLE TASK;