CREATE TABLE QB$QUEUE_NAMES
(
  QUEUE_ID   NUMBER        NOT NULL,
  QUEUE_NAME VARCHAR2(256) NOT NULL,
  PRIMARY KEY (QUEUE_ID)
);

CREATE UNIQUE INDEX QB$UNIQUE_NAME
ON QB$QUEUE_NAMES (QUEUE_NAME ASC);

CREATE SEQUENCE QB$SEQUENCE MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE QB$CHECKPOINT_SEQUENCE MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;


CREATE TABLE TASK (
  UUID       VARCHAR2(36) NOT NULL,
  JSON_VALUE CLOB         NULL,
  PRIMARY KEY (UUID)
)
NOCOMPRESS
;

CREATE TABLE DECISION (
  TASK_ID       VARCHAR2(36) NOT NULL,
  PROCESS_ID    VARCHAR2(36) NOT NULL,
  DESICION_JSON CLOB         NOT NULL,
  PRIMARY KEY (TASK_ID, PROCESS_ID)
)
NOCOMPRESS
;


CREATE TABLE TR_CHECKPOINTS (
  ID              NUMBER        NOT NULL,
  ENTITY_ID       VARCHAR2(36)  NOT NULL,
  ENTITY_TYPE     VARCHAR2(255) NOT NULL,
  TYPE_TIMEOUT    VARCHAR2(36)  NOT NULL,
  CHECKPOINT_TIME NUMBER        NOT NULL,
  PRIMARY KEY (ID)
)
NOCOMPRESS
;

ALTER TABLE DECISION ADD CONSTRAINT TASK_DECISION FOREIGN KEY (TASK_ID) REFERENCES TASK (UUID);

CREATE TABLE GRAPH (
  ID       VARCHAR2(36) NOT NULL,
  VERSION  NUMBER       NOT NULL,
  JSON_STR CLOB         NOT NULL,
  PRIMARY KEY (id)
)
NOCOMPRESS
;

CREATE TABLE GRAPH_DECISION (
  GRAPH_ID          VARCHAR2(36) NOT NULL,
  READY_ITEMS       CLOB         NOT NULL,
  MODIFICATION_JSON CLOB         NOT NULL,
  PRIMARY KEY (GRAPH_ID)
)
NOCOMPRESS
;

CREATE OR REPLACE TRIGGER TR_CHECKPOINTS_BI
BEFORE INSERT
ON TR_CHECKPOINTS
FOR EACH ROW
  BEGIN
    IF :NEW.id IS NULL
    THEN
      SELECT
        QB$CHECKPOINT_SEQUENCE.NEXTVAL
      INTO :NEW.id
      FROM DUAL;
    END IF;
  END;

CREATE TABLE process (
  process_id    VARCHAR2(36)  NOT NULL,
  start_task_id VARCHAR2(36)  NOT NULL,
  custom_id     VARCHAR2(256) NULL,
  start_time    NUMBER        NOT NULL,
  end_time      NUMBER        NULL,
  state         NUMBER        NOT NULL,
  return_value  CLOB          NULL,
  PRIMARY KEY (process_id)
)
NOCOMPRESS
;

ALTER TABLE process ADD CONSTRAINT custom_id_uq UNIQUE (custom_id);
/

