DROP TABLE qb$multiplier;
CREATE TABLE qb$multiplier (
  TASK_ID VARCHAR(36) NOT NULL ENABLE,
  STATUS_ID NUMBER NOT NULL ENABLE,
  TASK_LIST VARCHAR(54) NOT NULL ENABLE,
  DATE_START TIMESTAMP,
  INSERT_DATE TIMESTAMP,
  PRIMARY KEY (TASK_ID)
);
CREATE INDEX qb$multiplier_IND ON qb$multiplier (STATUS_ID, DATE_START);

DROP TABLE qb$number_generator;
CREATE TABLE qb$number_generator (
  TASK_ID VARCHAR(36) NOT NULL ENABLE,
  STATUS_ID NUMBER NOT NULL ENABLE,
  TASK_LIST VARCHAR(54) NOT NULL ENABLE,
  DATE_START TIMESTAMP,
  INSERT_DATE TIMESTAMP,
  PRIMARY KEY (TASK_ID)
);
CREATE INDEX qb$number_generator_IND ON qb$number_generator (STATUS_ID, DATE_START);

DROP TABLE qb$summarizer;
CREATE TABLE qb$summarizer (
  TASK_ID VARCHAR(36) NOT NULL ENABLE,
  STATUS_ID NUMBER NOT NULL ENABLE,
  TASK_LIST VARCHAR(54) NOT NULL ENABLE,
  DATE_START TIMESTAMP,
  INSERT_DATE TIMESTAMP,
  PRIMARY KEY (TASK_ID)
);
CREATE INDEX qb$summarizer_IND ON qb$summarizer (STATUS_ID, DATE_START);

DROP TABLE qb$math_action_decider;
CREATE TABLE qb$math_action_decider (
  TASK_ID VARCHAR(36) NOT NULL ENABLE,
  STATUS_ID NUMBER NOT NULL ENABLE,
  TASK_LIST VARCHAR(54) NOT NULL ENABLE,
  DATE_START TIMESTAMP,
  INSERT_DATE TIMESTAMP,
  PRIMARY KEY (TASK_ID)
);
CREATE INDEX qb$math_action_decider_IND ON qb$math_action_decider (STATUS_ID, DATE_START);



