CREATE TABLE TSK_NOTIFICATION_CFG (
    ID                NUMBER NOT NULL PRIMARY KEY,
    TYPE              VARCHAR2(200 char) NOT NULL,
    ACTORS_JSON       CLOB NOT NULL,
    EMAILS_JSON       CLOB NOT NULL,
    CHANGE_DATE     TIMESTAMP(6) NOT NULL
);

COMMENT ON COLUMN TSK_NOTIFICATION_CFG.ID IS 'Config unique identifier';
COMMENT ON COLUMN TSK_NOTIFICATION_CFG.TYPE IS 'Configuration type';
COMMENT ON COLUMN TSK_NOTIFICATION_CFG.ACTORS_JSON IS 'JSON representation of actors of interest list';
COMMENT ON COLUMN TSK_NOTIFICATION_CFG.EMAILS_JSON IS 'JSON representation of notification emails';
COMMENT ON COLUMN TSK_NOTIFICATION_CFG.CREATION_DATE IS 'Row data change date';

CREATE SEQUENCE SEQ_TSK_NOTIFICATION_CFG MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE OR REPLACE TRIGGER TSK_NOTIFICATION_CFG_BI
BEFORE INSERT
ON TSK_NOTIFICATION_CFG
FOR EACH ROW
  BEGIN
    IF :NEW.id IS NULL
    THEN
      SELECT
        SEQ_TSK_NOTIFICATION_CFG.NEXTVAL
      INTO :NEW.id
      FROM DUAL;
    END IF;
  END;
/
