DROP TABLE TSK_PROCESS;

DROP TABLE TSK_BROKEN_PROCESSES;
DROP SEQUENCE SEQ_TSK_BROKEN_PROCESSES;

DROP TABLE TSK_SCHEDULED;
DROP SEQUENCE SEQ_TSK_SCHEDULED;

DROP TABLE TSK_INTERRUPTED_TASKS;
DROP SEQUENCE SEQ_TSK_INTERRUPTED_TASKS;

DROP TABLE TSK_NFN_TRIGGERS;
DROP SEQUENCE SEQ_TSK_NFN_TRIGGERS;

DROP TABLE TSK_NFN_SUBSCRIPTIONS;
DROP SEQUENCE SEQ_TSK_NFN_SUBSCRIPTIONS;

DROP TABLE TSK_NFN_LINKS;
DROP SEQUENCE SEQ_TSK_NFN_LINKS;

EXIT;